#!/usr/bin/env python

nombre1 = input('Entrez un premier nombre : ')
nombre2 = input('Entrez un deuxième nombre : ')
print('Vous avez entré ' + nombre1 + ' et ' + nombre2 + '.')
print(int(nombre1) + int(nombre2))